/**
*This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
*Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
*/

package
{
    import flash.display.Sprite;
    
    import flexUnitTests.com.pcup.PcupTestSuite;
    import flexUnitTests.com.pcup.utils.FrameScriptManagerTest;
    import flexUnitTests.com.pcup.utils.UtilsTestSuite;
    
    public class FlexUnitCompilerApplication extends Sprite
    {
        
        private var flexUnitTests_com_pcup_utils_FrameScriptManagerTest_obj:flexUnitTests.com.pcup.utils.FrameScriptManagerTest;
        private var flexUnitTests_com_pcup_utils_UtilsTestSuite_obj:flexUnitTests.com.pcup.utils.UtilsTestSuite;
        private var flexUnitTests_com_pcup_PcupTestSuite_obj:flexUnitTests.com.pcup.PcupTestSuite;
    }
}